name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build:prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./app
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEARN_COUNTRY_QUIZ }}'
          projectId: learn-country-quiz
          channelId: live
